endpoints:
    "/github":
        script: |
          import se.elipsion.tutter.modules.github.*;
          Object o = Util.gitHubEnterprise("https://ghe.spotify.net/api/v3/");
          print(o);
          print(owners);
        parameters:
          accessToken: "DEADBEEF42"
          votes: 2
          owners:
              - elipsion
              - olle
              - guidou

